SELECT Go.IdP, LPTC.IdP, [1EQ].IdP, [6Fuga].IdP, [2UQ].IdP, [1EQ].IdT, [2UQ].IdT, [6Fuga].IdT
FROM ((([Go] INNER JOIN LPTC ON (Go.IdP = LPTC.IdP) AND (Go.IdP = LPTC.IdP)) INNER JOIN 2UQ ON LPTC.IdP = [2UQ].IdP) INNER JOIN 1EQ ON LPTC.IdP = [1EQ].IdP) INNER JOIN 6Fuga ON LPTC.IdP = [6Fuga].IdP
GROUP BY Go.IdP, LPTC.IdP, [1EQ].IdP, [6Fuga].IdP, [2UQ].IdP, [1EQ].IdT, [2UQ].IdT, [6Fuga].IdT
ORDER BY LPTC.IdP;
