SELECT Go.IdP, LPTC.IdT, LPTC_1.IdT, LPTC_2.IdT, LPTC_3.IdT
FROM ((([Go] INNER JOIN LPTC ON Go.IdP = LPTC.IdP) INNER JOIN LPTC AS LPTC_1 ON Go.IdP = LPTC_1.IdP) INNER JOIN LPTC AS LPTC_2 ON Go.IdP = LPTC_2.IdP) INNER JOIN LPTC AS LPTC_3 ON Go.IdP = LPTC_3.IdP
GROUP BY Go.IdP, LPTC.IdT, LPTC_1.IdT, LPTC_2.IdT, LPTC_3.IdT
HAVING (((LPTC.IdT)=2) AND ((LPTC_1.IdT)=3) AND ((LPTC_2.IdT)=6) AND ((LPTC_3.IdT)=10));
