SELECT LPTC.IdP, Max(LPTC.Data) AS MaxDiData, LPTC.IdT, Max(LPTC.Ora) AS MaxDiOra, Max(LPTC.IdC) AS MaxDiIdC
FROM LPTC INNER JOIN [Go] ON LPTC.IdP = Go.IdP
GROUP BY LPTC.IdP, LPTC.IdT
HAVING (((LPTC.IdP) In (SELECT LPTC.IdP
FROM LPTC
WHERE (((LPTC.IdT)=3));
)) AND ((LPTC.IdT)=2)) OR (((LPTC.IdT)=3))
ORDER BY LPTC.IdP, Max(LPTC.Data), LPTC.IdT;
