SELECT LPTC.IdP, LPTC.Data, LPTC.IdT, LPTC.Ora, LPTC.IdC
FROM LPTC INNER JOIN [Go] ON LPTC.IdP = Go.IdP
GROUP BY LPTC.IdP, LPTC.Data, LPTC.IdT, LPTC.Ora, LPTC.IdC
HAVING (((LPTC.IdP) In (SELECT LPTC.IdP
FROM LPTC
WHERE (((LPTC.IdT)=6));
)) AND ((LPTC.IdT)=3))
ORDER BY LPTC.IdP, LPTC.Data, LPTC.IdT;
