SELECT LPTC.IdP, LPTC.Data, LPTC.IdT, LPTC.Ora, LPTC.IdC
FROM LPTC INNER JOIN [Go] ON LPTC.IdP = Go.IdP
WHERE (((LPTC.Data) Between #01/01/2021# And #31/01/2021# AND ((LPTC.[IdT])=10 Or (LPTC.[IdT])=7)))
ORDER BY LPTC.IdP, LPTC.Data, LPTC.IdT;
